### ISSUE TITLE
Scale option 

### ISSUE THREAD

**Issue by netmastan** [benwinding/pdfstamp#2]
Hi, is it possible to add a Scale option?
I'm saving an object position ie a square using fabric.js. Basically, saving the object's location in a JSON file. When I went to stamp something in the same location as the object using this tool, the object appears in a different positoin. I think this is because the object's position was saved on a scale 1.5. It would be nice to have this option. I'm sure it will be a mighty stamper.

**Comment by benwinding** [comment]
Hi @netmastan,
Yes this is possible using the `--zoom <value>` option, where `<value>` is the percentage of the page's width. 
E.g. --zoom 20 will use a signature that is 20% of the page width.
Let me know if that works for you 👍

**Comment by netmastan** [comment]
Hi @benwinding, it will zoom the signature, not the PDF. I wanted something like this

pdfstamp stamp \                                                                                                      
--input ./input.pdf \ 
-- scale 1.5
-- zoom 20                                                                                 
--signature ./signature.png \                                                      
--output ./output.pdf \                                
--page 2 \                       
--bottom 300 \
--left 200

**Comment by benwinding** [comment]
Oh, true, I accidentally had the pagewidth hardcoded here:

https://github.com/benwinding/pdfstamp/blob/aaa1b8d1a761fe59c543183fed3b487aba0fe4d3/index.js#L123-L124

Try version: `pdfstamp@1.0.9` and let me know if that fixes it 👌

**Comment by netmastan** [comment]
After updating getting this error in Windows. I have not tried in Mac or other OS

C:\Users\coder>pdfstamp
C:\Users\coder\AppData\Roaming\npm\node_modules\pdfstamp\index.ts:1
import program from "commander";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\coder\AppData\Roaming\npm\node_modules\pdfstamp\node_modules\ts-node\src\index.ts:1300:43)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\coder\AppData\Roaming\npm\node_modules\pdfstamp\entry.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)

**Comment by benwinding** [comment]
Okay, sorry about that (typescript errors)

Please try the newer version `pdfstamp@1.0.13`
